### ISSUE TITLE
Demo Environment: "SaltReqTimeoutError: Message timed out"

### ISSUE THREAD

**Issue by tovin07** [UtahDave/salt-vagrant-demo#28]
Hello,

I'm newbie to Salt here.
I've followed up this tutorial (https://docs.saltstack.com/en/getstarted/fundamentals/index.html).
However, when I run `salt "*" state.apply nettools`, after a few minutes, I got this.
Don't know what it is. Don't know how to fix it.

What's wrong with my demo environment?

Thanks!

**My top.sls:**

``` yaml
base:
  '*':
    - common
```

**My nettools.sls:**

``` yaml
install_network_packages:
  pkg.installed:
    - pkgs:
      - rsync
      - lftp
      - curl
```

**Ping results:**

``` yaml
root@saltmaster:/srv/salt# salt "*" test.ping
minion2:
    True
minion1:
    True
```

**Bash output when run salt:**

``` bash
root@saltmaster:/srv/salt# ls -lha
total 12K
drwxr-xr-x 1 vagrant vagrant  170 Jun 10 15:47 .
drwxr-xr-x 4 root    root    4.0K Jun 10 12:22 ..
drwxr-xr-x 1 vagrant vagrant  136 Jun 10 12:10 common
-rw-r--r-- 1 vagrant vagrant   95 Jun 10 15:47 nettools.sls
-rw-r--r-- 1 vagrant vagrant   26 Jun 10 15:27 top.sls
root@saltmaster:/srv/salt# salt "*" state.apply nettools
minion2:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1317, in _thread_return
        return_data = executor.execute()
      File "/usr/lib/python2.7/dist-packages/salt/executors/direct_call.py", line 28, in execute
        return self.func(*self.args, **self.kwargs)
      File "/usr/lib/python2.7/dist-packages/salt/modules/state.py", line 445, in apply_
        return sls(mods, **kwargs)
      File "/usr/lib/python2.7/dist-packages/salt/modules/state.py", line 909, in sls
        mocked=kwargs.get('mock', False))
      File "/usr/lib/python2.7/dist-packages/salt/state.py", line 3295, in __init__
        BaseHighState.__init__(self, opts)
      File "/usr/lib/python2.7/dist-packages/salt/state.py", line 2376, in __init__
        self.opts = self.__gen_opts(opts)
      File "/usr/lib/python2.7/dist-packages/salt/state.py", line 2403, in __gen_opts
        mopts = self.client.master_opts()
      File "/usr/lib/python2.7/dist-packages/salt/fileclient.py", line 1353, in master_opts
        return self.channel.send(load)
      File "/usr/lib/python2.7/dist-packages/salt/utils/async.py", line 75, in wrap
        ret = self._block_future(ret)
      File "/usr/lib/python2.7/dist-packages/salt/utils/async.py", line 85, in _block_future
        return future.result()
      File "/usr/lib/python2.7/dist-packages/tornado/concurrent.py", line 215, in result
        raise_exc_info(self._exc_info)
      File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 876, in run
        yielded = self.gen.throw(*exc_info)
      File "/usr/lib/python2.7/dist-packages/salt/transport/zeromq.py", line 270, in send
        ret = yield self._crypted_transfer(load, tries=tries, timeout=timeout)
      File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 870, in run
        value = future.result()
      File "/usr/lib/python2.7/dist-packages/tornado/concurrent.py", line 215, in result
        raise_exc_info(self._exc_info)
      File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 876, in run
        yielded = self.gen.throw(*exc_info)
      File "/usr/lib/python2.7/dist-packages/salt/transport/zeromq.py", line 238, in _crypted_transfer
        ret = yield _do_transfer()
      File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 870, in run
        value = future.result()
      File "/usr/lib/python2.7/dist-packages/tornado/concurrent.py", line 215, in result
        raise_exc_info(self._exc_info)
      File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 876, in run
        yielded = self.gen.throw(*exc_info)
      File "/usr/lib/python2.7/dist-packages/salt/transport/zeromq.py", line 224, in _do_transfer
        tries=tries,
      File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 870, in run
        value = future.result()
      File "/usr/lib/python2.7/dist-packages/tornado/concurrent.py", line 215, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
    SaltReqTimeoutError: Message timed out
minion1:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1317, in _thread_return
        return_data = executor.execute()
      File "/usr/lib/python2.7/dist-packages/salt/executors/direct_call.py", line 28, in execute
        return self.func(*self.args, **self.kwargs)
      File "/usr/lib/python2.7/dist-packages/salt/modules/state.py", line 445, in apply_
        return sls(mods, **kwargs)
      File "/usr/lib/python2.7/dist-packages/salt/modules/state.py", line 930, in sls
        high_, errors = st_.render_highstate({saltenv: mods})
      File "/usr/lib/python2.7/dist-packages/salt/state.py", line 3068, in render_highstate
        sls, saltenv, mods, matches)
      File "/usr/lib/python2.7/dist-packages/salt/state.py", line 2735, in render_state
        state_data = self.client.get_state(sls, saltenv)
      File "/usr/lib/python2.7/dist-packages/salt/fileclient.py", line 475, in get_state
        dest = self.cache_file(path, saltenv, cachedir=cachedir)
      File "/usr/lib/python2.7/dist-packages/salt/fileclient.py", line 178, in cache_file
        return self.get_url(path, '', True, saltenv, cachedir=cachedir)
      File "/usr/lib/python2.7/dist-packages/salt/fileclient.py", line 575, in get_url
        url, dest, makedirs, saltenv, cachedir=cachedir)
      File "/usr/lib/python2.7/dist-packages/salt/fileclient.py", line 1154, in get_file
        data = self.channel.send(load)
      File "/usr/lib/python2.7/dist-packages/salt/utils/async.py", line 75, in wrap
        ret = self._block_future(ret)
      File "/usr/lib/python2.7/dist-packages/salt/utils/async.py", line 85, in _block_future
        return future.result()
      File "/usr/lib/python2.7/dist-packages/tornado/concurrent.py", line 215, in result
        raise_exc_info(self._exc_info)
      File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 876, in run
        yielded = self.gen.throw(*exc_info)
      File "/usr/lib/python2.7/dist-packages/salt/transport/zeromq.py", line 270, in send
        ret = yield self._crypted_transfer(load, tries=tries, timeout=timeout)
      File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 870, in run
        value = future.result()
      File "/usr/lib/python2.7/dist-packages/tornado/concurrent.py", line 215, in result
        raise_exc_info(self._exc_info)
      File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 876, in run
        yielded = self.gen.throw(*exc_info)
      File "/usr/lib/python2.7/dist-packages/salt/transport/zeromq.py", line 238, in _crypted_transfer
        ret = yield _do_transfer()
      File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 870, in run
        value = future.result()
      File "/usr/lib/python2.7/dist-packages/tornado/concurrent.py", line 215, in result
        raise_exc_info(self._exc_info)
      File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 876, in run
        yielded = self.gen.throw(*exc_info)
      File "/usr/lib/python2.7/dist-packages/salt/transport/zeromq.py", line 224, in _do_transfer
        tries=tries,
      File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 870, in run
        value = future.result()
      File "/usr/lib/python2.7/dist-packages/tornado/concurrent.py", line 215, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
    SaltReqTimeoutError: Message timed out
```

**Comment by tovin07** [comment]
As for today, `salt "*" state.apply nettools` works fine. I still do not know why.

**Comment by UtahDave** [comment]
@tovin07 Did a newer version of Salt start getting installed? There may have been a bug fixed. Can we close this issue now?

**Comment by UtahDave** [comment]
After some more testing I believe this bug was fixed by a bugfix release of Salt. I'm going to close this issue for now. If you run into this problem again, please comment here and we'll reopen.

Thanks!
